### ISSUE TITLE
Prevent interaction with items that are currently being duplicated

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#128]
When duplicating items, the new items created are immediately available to the user and can be edited, causing conflicts with persistence as the duplicate operation is still occurring.

The new object created via Duplicate should not be visible or available for interaction until the entire recursive operation has completed.  When duplicate is a recursive action, it should create the entire tree structure before adding the new object to it's parent's composition.

**Comment by charlesh88** [comment]
Do we or can we have any feel for the timescale of the operation? I see two ways to handle this, we may want to implement both if the system is able to estimate the time that would be needed for any given operation. I also see the following solutions being applied as a general design pattern for operations that take time to complete.

Approaches:
1. "You vill vait": when the user pushes the button or makes the menu choice that initiates the operation, modally lock the entire app with a modal dialog that says something like "Operation in progress... please standby" and includes a (real or fake) progress indicator. There may be a Cancel button (if we can support it) that cancels the operation - but, and this is important: Cancel would need to COMPLETELY cancel the operation. It's no good if Cancel only stops the operation, with (for example) 2 out of 5 items duplicated.
2. "We'll tell you when it's ready": when the user pushes the button or makes the menu choice that initiates the operation, display a non-modal, unobtrusive but clearly visible message that the operation is in progress. Don't immediately add any objects at all to the tree. The message indicator may or may not include a Cancel button. So, let's say the user dupes a folder that contains a large number of nested children. When the operation completes, a new message is flashed up stating such, and the new object and its children is refreshed into the tree. This message might include a helpful link to the object (or top level of a hierarchy) that was created.
3. Same as 2, but any items (or the top level of a deep hierarchy being duplicated) resulting from the operation are immediately created, but display a pending state. The message indicator may or may not include a Cancel button. So, let's say the user dupes a folder that contains a large number of nested children. Once the operation is initiated, they'd see the top level of the folder immediately added to the tree, but with a Pending style. Clicking on the folder may or may not display anything in the view area; we could make pending tree items non-selectable. Alternately, we could have a pending view for objects that doesn't include any edit affordances. Needless to say, the context menu for pending items is not available, or must be contextual to that state.

Option 2 and 3 are my preference and are the more modern approach - they asynchronously allow the user to continue on their way, with a tea kettle whistle to tell you when the water is ready. I actually think 2 is better and less complex than 3, but I include it here in case it's something we need to do given how the system operates. Option 1 is probably simpler to implement and is fine if the operations involved can be under 15 to 20 seconds to complete.

We have [UI design](https://drive.google.com/drive/u/1/folders/0BxkN5uiYOuicU1F6MXBQb3lQS3c) on pgs. 9 and 10 for the messaging described here; it was included as part of move/copy/link and in my opinion will be really necessary if as well if we ever implement drag within or into the tree.

**Comment by larkin** [comment]
@charlesh88 I am all about number 2, and number 3 seems like an iteration of the same functionality that could be implemented later.

For all options, a full cancel option is necessary-- half-way copies are no good.

(number 3 is very modern, OSX does this for file copies and downloads and its a pretty great experience, IMO)

**Comment by VWoeltjen** [comment]
I vote for Option 4, where we show a blocking dialog with no progress indicator while Duplicate is happening. An X icon is available in the top-right corner; the user can click on this to receive a mild electric shock in order to learn patience.

From a development effort perspective, Option 2 pops out as a likely to require a little more since we don't have any visual indicators like that yet (whereas we do have a tree and dialogs, although we'd need to add some new display functionality in either of those to complete Option 1 or Option 2.) But we do want to have support for non-blocking informational messages in the platform, so that's only a soft knock against it.

I like Option 3 the best from a UX perspective, but it's also the most likely to involve gotchas. One thing we haven't run into yet (but might) with long-running duplicates is the duplication of intermediary states. Let's say that the user is looking at a tree like:

```
+ A
|
+-+ B
  |
  + C
```

And decides to duplicate A. They see "Copy of A" (or similar) appear with some visual indication that it is pending (spinning circle, etc.)

Meanwhile, they think "I have my Copy of A now, I can go ahead and remove C from the original A." If that original duplicate is particularly slow (or, more realistically, if the duplicated tree is particularly large) it's possible that they will remove C before it has been recursively copied into the new A. 

Unfortunately, there is a risk of this even if we throw a big blocking electrocuting dialog in front of everything, because there's nothing stopping them (or someone with equivalent permissions) from going and deleting C before the script that is doing the copying ever sees it. This is also probably not the only strange behavior that might be possible if we allow the user to do normal stuff while a Duplicate is running in the background, but it's a good example (particularly because there's a plausible reason for the user to do that specific thing.)

That having been said, I think a blocking dialog (or at least an informational indicator, like Option 2) is better here, because if the user does go and delete C while this is showing, they at least had a nice visual indicator that should have discouraged them from doing so. (The multi-user case is more daunting, but I don't think we can really prevent this - even with some elaborate locking strategy, another user might delete object C _just before_ the first user tries to duplicate object A, with the same apparent result in the end.)

To summarize:

Option | UX | Risk | Dev. Effort
-------|----|------|------
1 |  :disappointed: | :neutral_face: | :neutral_face: 
2 | :neutral_face: | :worried: | :unamused: 
3 | :smile: | :fearful: | :neutral_face: 

There's also a composite of Options 1 & 3 that we can consider where we throw a blocking dialog while the set of objects to be duplicated is _loaded_ (if it takes or is expected to take longer than 100ms), but show a pending object in the tree which the set of objects to be duplicated is _saved_. I think this may require some refinement of the algorithm used to implement duplicate, not sure.

Lastly, I think there's a variant of Option 3 where we show Copy of A in an expanded state and the user can actually watch the various items inside it fill in. I'm not sure if that provides enough visual feedback for the case I'm worried about or not, raising it as a possibility.

**Comment by larkin** [comment]
First, that table is amazing.

Second: trying my best to separate UI concerns from implementation details with #127.

At baseline, and completely separately from the UI, there are improvements to the duplicate operation that need to be made to make it more robust.  These improvements are **required** for any of the above ~~three~~ four options.  Duplicate will become a three stage operation:
1. recurse tree and get an in-memory copy of every object it needs to duplicate.
2. iterate through duplicated objects and persist them.
3. persist final change to parent composition, finalizing the copy action.

From the UI side, the components we need are:
1. A dialogue box for stage 1 that blocks user interaction and allows them to cancel. as during stage one the user shouldn't be modifying anything.
2. a progress indicator for stage 2, with a cancel button.
3. a notification at the completion of stage 3.

**Comment by charlesh88** [comment]
Discussion during tagup 9/21/15: scale could be minutes. We can do a dialog with text messages and simple progress bar articulating process.

**Comment by larkin** [comment]
Sending to @akhenry as per discussions today.

**Comment by akhenry** [comment]
I have a concern about switching to a "bottom-up" persistence strategy. If any step in persisting the object tree should fail, we create a ton (metric) of orphan objects, and that makes me sad (but Fagin very happy). The current strategy results in a bunch of redundant persists because each step in the copy is discrete and results in a valid object tree (this is not strictly true, persisting the child, and updating the composition of the parent are two discrete steps, but result in the creation of at most one orphan object).

**Comment by larkin** [comment]
The same is true of a top down copy, and in the top down copy, it has the downside of the user seeing an incomplete tree.  Orphan objects aren't all bad; in our current persistence paradigm an orphan object is the same as a deleted object.

In either case, we'll have to know how to handle persistence errors.  What sort of persistence errors are you seeing?

**Comment by akhenry** [comment]
Not seeing persistence errors, just thinking theoretically. Bottom up has an incomplete tree until the very last step (persisting the duplicated "root" object - that is, the object selected by the user for duplication). By contrast, top down has a valid tree at (almost) every step that on failure that is visible and thus could be cleaned up by the user with a delete.

I dunno, I'm probably worrying about something that will never happen : ) But it seems that because persisting each object in the tree relies on a network call, there is a non-trivial likelihood of failure. I suppose the ideal approach would be to build the entire object tree in memory and persist the whole thing in one bulk save operation.

**Comment by larkin** [comment]
Charles has said (and I do agree) that leaving a user with a half-copied tree is very confusing and undesirable.  As orphaned objects are invisible to users, I'd rather there be a bunch of orphans that can't be seen instead of a half-copied tree that a user must figure out themselves.

Even if we catch the error and clean up, we still have to contend with the possibility that a user could kill their browser 99% of the way through a copy, in which case I'd rather orphan all those objects instead of have an incomplete tree.

**Comment by larkin** [comment]
(yes in memory copy and single persist would be nice but hard to support with multiple persistence backends)

**Comment by akhenry** [comment]
No problem, I'll go with bottom-up, I agree that it's a better user experience.

**Comment by VWoeltjen** [comment]
Filed #194 to track the more general problem of these orphans. My general feeling about this is that I don't believe the client can handle this in all cases (without making even less-desirable trades), so if it is a problem, it should be solved with a garbage collector or similar. As a consequence, I think it's safe for client operations to assume that orphans are not a problem, or that they will be cleaned up by some other process.

**Comment by akhenry** [comment]
This issue might benefit from refactoring once https://github.com/nasa/openmctweb/issues/215 is implemented.

**Comment by akhenry** [comment]
This has been addressed by merged pull request https://github.com/nasa/openmctweb/pull/249

Copying is now performed in a bottom-up fashion, with copied objects only added to the tree as a final step once all persistence has been successfully compelted.

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  Notification and progress bar on copying even a relatively large collection of items go so quickly, it is difficult to verify that this blocks my ability to tamper during the duplicate action.
