### ISSUE TITLE
[Generic Search] Misc. performance issues

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#141]
Observing miscellaneous performance issues with generic search running on a demo deployment with a database of ~22000 index-able domain objects.

Subjectively, interactions with the UI are noticeably sluggish while indexing occurs (during the first ~45s after page load.) Operations which require HTTP requests are particularly effected (this may include any operation which loads new markup for the first time, such as launching a dialog.)

Compared memory usage (as reported by recording heap allocations in Chrome) and CPU usage (as reported by `top` for the relevant Chrome tab) during the first minute of application load:

                                 | CPU % | Mem. Usage
---------------------------------|-------|-----------
`node app.js`                    | ~150% | 235MB
`node app.js -x platform/search` | ~10%  | 13.7MB

There is a bit of a mitigating factor insofar as memory usage is likely to climb during normal usage after the first minute, as more domain objects are loaded as a result of the user's browsing action; since these will be cached as a byproduct of the search indexing, memory usage is unlikely to continue to climb much from 235MB with generic search enabled, but is likely climb toward 235MB with generic search disabled.

**Comment by VWoeltjen** [comment]
After indexing has completed, CPU % does fall back down to the normal (~10%) range. Moving indexing to a shared worker may be a reasonable approach to mitigating this, particularly if combined with other performance optimizations which reduce CPU utilization during the initial minute of indexing.

That said, I think we will ultimately want to move away from using generic search in production, except perhaps for very small-scale deployments. Telemetry dictionaries alone can very often exceed 20,000 domain objects in size, and in some cases we will want to expose multiple dictionaries in the same application instance; user-created objects will accrue over time (we've seen ~2000 user objects get created over a few months of somewhat light use by 5-10 actively-creating users); and other dense/deep non-user-created trees (similar to telemetry dictionaries) are also reasonable to expect. 

100,000 domain objects seems like a very realistic number; 1,000,000 is worth considering as a possibility (at least as a stressing case for margin.) Assuming the above numbers grow linearly (which is a reasonable expectation; indexing cannot be better than O(n) for n objects), 1-10GB of memory utilization and 4-40min of full CPU utilization would be anticipated based on the above numbers.

**Comment by larkin** [comment]
Did you wait for a garbage collect after indexing?

I am willing to bet that there is a lot of unused memory reclaimed that is not directly related to search itself, but to inefficiencies in our domain object model.

I'd like to take a look at search performance, I think all these issues can be resolved.

**Comment by VWoeltjen** [comment]
The memory numbers were Retained Size (e.g. not eligible for GC.) Stopped profiling 5-10sec after memory usage dropped back down, taking that as evidence that indexing was complete (would expect any references which were being held temporarily to have been released by then.)

This doesn't mean that this was all being held by search, necessarily; one byproduct of indexing the universe is that you also exercise every inefficiency associated with every type of domain object, every model provider, etc... 

There are pros and cons to that.

**Comment by larkin** [comment]
Related but not necessarily a duplicate:  https://github.com/nasa/openmctweb/issues/91

Also realizing that the search indexing listens for mutations on all objects, which retains a references to every object with mutation, which... could be a problem.

**Comment by VWoeltjen** [comment]
The topics used to listen to mutation don't directly retain references to the domain object (or to the mutation capability); they do retain references to all listeners, though, and I suppose some of those could retain references to the objects. The only case where this occurs in platform is `TelemetrySubscription`, but those listeners appear to be correctly detached, so should only be present for objects with some active telemetry-driven view

**Comment by VWoeltjen** [comment]
...ah, but there is (indirectly) a reference that gets retained to the domain objects being listened-to within GenericSearchProvider itself. It's a [rather sneaky kind of memory leak](http://info.meteor.com/blog/an-interesting-kind-of-javascript-memory-leak) resulting from the reuse of closure scope - the [listener itself](https://github.com/nasa/openmctweb/blob/d6fe543c16ba32c637b2106aaf3da07e0e49929b/platform/search/src/services/GenericSearchProvider.js#L149) doesn't reference the object being listened to via closure scope, but [another function in the same scope](https://github.com/nasa/openmctweb/blob/d6fe543c16ba32c637b2106aaf3da07e0e49929b/platform/search/src/services/GenericSearchProvider.js#L132) does. Both functions share the same closure, so the reference to the domain object in the latter causes it to be retained in the former. Think I can address that by moving functions around.

**Comment by VWoeltjen** [comment]
After making the change mentioned in previous comment, see 190MB retained after 1min. (Without that change, still seeing 232MB after 1min., consistent with original numbers.) So, that accounts for ~20% of the memory usage there.

**Comment by VWoeltjen** [comment]
Still another 30MB on mutation listeners generally. Think this could be removed almost entirely by adding a more general-purpose event messaging bus, and having GenericSearch just listen to one general-purpose "mutation" event

**Comment by VWoeltjen** [comment]
For the CPU usage, profiling points at the digest cycle. Looking into digest counts; during first 45s of application running, we see:

 | Digests / sec
------------ | -------------
w/o Search | 66
w/ Search  | 105
w/ Mod Search (below) | 52

Search modification is to [the timeout used to split up loading of children](https://github.com/nasa/openmctweb/blob/d6fe543c16ba32c637b2106aaf3da07e0e49929b/platform/search/src/services/GenericSearchProvider.js#L132-L144) to:

```javascript
$timeout(function () {
    node.useCapability('composition').then(indexItems);
}, 0, false);
```

Key point is adding the `false` argument to prevent triggering a digest cycle. Removed the inner timeout for simplicity, but the decreased digest count also comes along with (subjectively) decreased performance. Unclear why that happens; will try adding it back in. The fact that the digest count is lower than without search is also unexpected; guessing that this is resulting in more time spent per digest, decreasing the number of digests that _can_ run per second (as opposed to how many actually get triggered.)

**Comment by VWoeltjen** [comment]
Trying the above with different metrics. Measuring by:

* Starting CPU profiling in Chrome at page load
* Watching `top` to see the tab's CPU usage fall below 20%
* Stopping CPU profiling

Running... | Idle time (s) | Total time (s) | Idle time (%)
---- | ---- | ---- | ----
w/ Search | 12.7 | 36 | 35
w/o Search &dagger; | 29.6 | 32 | 92.5
w/ Mod Search | 17.9 | 95 | 18.8
w/ Search w/o digests &Dagger; | 13.9 | 45 | 30.1

&dagger; CPU time in this configuration starts below 20%, so just waited for a comparable total time.
&Dagger; In this case, leaving the inner timeout in place and only adding a `false` parameter to suppress invocation of `$apply`

The results are counter-intuitive but reasonably reproducible; don't think it makes sense to continue looking at this specifically.

**Comment by VWoeltjen** [comment]
Tried rewriting the indexing process for GenericSearch; general approach used is as follows:

* Maintain a set of ids to be indexed.
* Maintain a set of ids which have already been scheduled for indexing, to exclude these from duplicate indexing requests.
* Use a throttled indexing function to load and index items by identifier, doing a small number at a time. 
* When an object is indexed, check for a `composition` field in its model and schedule those ids for indexing.

This gives some nicer performance characteristics using the same measurement approach above:

Running... | Idle time (s) | Total time (s) | Idle time (%)
---- | ---- | ---- | ----
w/ Throttled indexing | 21 | 30 | 70

Currently testing to verify that this behaves similarly to the existing implementation.

Notably, since this is indexing by the `composition` field of the model instead of the capability, this has some undesirable characteristics:

* Need to know specifics of domain object model instead of programming against capabilities. Think this is justified since (a) this is a platform component, and (b) the performance improvements are significant.
* Domain objects which are indexed have no context. Existing generic search implementation doesn't use context either, however, so this is no different. Still, this approach would need to change if we were to implement a search that exposes both linked instances and originals as separate search results (currently, only originals are shown)

**Comment by larkin** [comment]
This sounds like a very good baseline for the indexing process, while allowing small chunks of processing to be done in each timeout.

On a more subjective measure, is the interface now more responsive during indexing?

Also wondering: does the throttling simply restrict the number of index calls that are issued per second? Or does it limit to a certain number of concurrent index operations per second (e.g index operations are asynchronous). Seems that the latter option could control the amount of background processing in such a way that it would never hit performance issues.

On a separate note, it would be great if we could use requirejs in webworkers to reuse entire services and sets of code, such that we could move the entire index operation to the search worker and not have to do the heavy lifting in the main thread.

Pete

On Sep 29, 2015, at 3:55 PM, Victor Woeltjen <notifications@github.com<mailto:notifications@github.com>> wrote:


Tried rewriting the indexing process for GenericSearch; general approach used is as follows:

  *   Maintain a set of ids to be indexed.
  *   Maintain a set of ids which have already been scheduled for indexing, to exclude these from duplicate indexing requests.
  *   Use a throttled indexing function to load and index items by identifier, doing a small number at a time.
  *   When an object is indexed, check for a composition field in its model and schedule those ids for indexing.

This gives some nicer performance characteristics using the same measurement approach above:

Running...      Idle time (s)   Total time (s)  Idle time (%)
w/ Throttled indexing   21      30      70

Currently testing to verify that this behaves similarly to the existing implementation.

Notably, since this is indexing by the composition field of the model instead of the capability, this has some undesirable characteristics:

  *   Need to know specifics of domain object model instead of programming against capabilities. Think this is justified since (a) this is a platform component, and (b) the performance improvements are significant.
  *   Domain objects which are indexed have no context. Existing generic search implementation doesn't use context either, however, so this is no different. Still, this approach would need to change if we were to implement a search that exposes both linked instances and originals as separate search results (currently, only originals are shown)

**Comment by VWoeltjen** [comment]
Yep, does seem more responsive in general during indexing. I do hit some stalls during indexing (I believe this is occurs when a dictionary gets loaded) but I'm only seeing this once or twice per page load now.

Also, it does limit the number of concurrent calls per second - a new batch is not issued until the previous batch has been indexed. It's not precisely a items-per-second; there's an interval before the next batch is handled, and a batch size, so interval-times-size almost gets you items-per-second, except that the interval starts _after_ a previous batch has loaded. I believe this is appropriate, because some `getObjects` calls really do use significant CPU time (e.g. when dictionaries are loaded) and this ensures that there is some breathing room between those calls.

**Comment by larkin** [comment]
So if I understand you correctly, items per second is a function of (a) the latency of asynchronous operations, and (b) the max number of concurrent operations, where (b) itself is not clearly defined because concurrent requests are queued in batches.

It seems that removing batching of concurrent requests (but having a queue and limit max concurrent requests) would better utilize resources in cases where some requests take longer than others.

With object providers based on http requests, there will already be a maximum number of concurrent connections allowed by the user agent. Mismatches between this and our specified batch size could greatly slow down processing speed. (E.g if max connections is 10 and we batch at 11).

With object providers based on websockets, it is limited only by the back end's ability to respond quickly/process different messages concurrently.

Pete

On Sep 29, 2015, at 4:59 PM, Victor Woeltjen <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep, does seem more responsive in general during indexing. I do hit some stalls during indexing (I believe this is occurs when a dictionary gets loaded) but I'm only seeing this once or twice per page load now.

Also, it does limit the number of concurrent calls per second - a new batch is not issued until the previous batch has been indexed. It's not precisely a items-per-second; there's an interval before the next batch is handled, and a batch size, so interval-times-size almost gets you items-per-second, except that the interval starts after a previous batch has loaded. I believe this is appropriate, because some getObjects calls really do use significant CPU time (e.g. when dictionaries are loaded) and this ensures that there is some breathing room between those calls.

**Comment by VWoeltjen** [comment]
Playing around with different parameterizations for the above; particularly, how many objects to index per batch (size), and how long to wait between indexing another batch (interval).

Thinking a good target CPU utilization is 33%, with 50% being acceptable. Also would like to get time of ~1min, although under 2min seems reasonable given prior numbers

Size | Interval (ms) | CPU% | Time (s)
-----|-----|-----|-----
1000 | 100 | 95-100 :x: | 68 :ok:
500 | 200 | 60-66 :x: | 58 :white_check_mark: 
300 | 200 | 40-55 :x: | 70 :ok: 
80 | 75 | 45-50 :ok: | 85 :ok:
60 | 75 | 40-45 :ok: | 100 :ok:
50 | 70 | 37-42 :ok: | 110 :ok:
40 | 50 | 50-66 :x: | 107 :ok:
40 | 75 | 35-45 :ok: | 130 :x:
40 | 100 | 40-45 :ok: | 160 :x:
20 | 100 | 25-33 :white_check_mark: | 283 :x: 



Note that CPU% above is a generalization; in most cases, there's an early peak near 100% for the first few seconds after the application loads. Time measured is that utilization that typically appears after this initial peak has passed but before indexing has completed (observed via `top`)

**Comment by VWoeltjen** [comment]
@larkin - I see what you mean, let me try that approach and see how it compares to the above (particularly since I'm not in love with the numbers I'm getting with that approach)

**Comment by VWoeltjen** [comment]
Issuing separate `getObjects` calls per-id, with a maximum current number of ids (size) and indicated interval between new requests gives:

Size | Interval (ms) | CPU% | Time (s)
-----|-----|-----|-----
1000 | 10 | 100-120 :x: | 39 :white_check_mark: 
300 | 200 | 45-55 :x: | 63 :ok: 
250 | 100 | 65-70 :x: | 47 :white_check_mark: 
100 | 200 | 33-40 :ok: | 121 :x:
100 | 180 | 33-40 :ok: | 108 :ok:
100 | 150 | 37-45 :ok: | 101 :ok:
100 | 100 | 45-50 :ok: | 73 :ok: 
75 | 150 | 35-40 :ok: | 125 :x:
50 | 70 | 45-50 :ok: | 100 :ok:
40 | 75 | 43-47 :ok: | 128 :x:
40 | 50 | 50-55 :x: | 99 :ok:
20 | 100 | 30-35 :white_check_mark: | 286 :x:
10 | 20 | 50-60 :x: | 172 :x:

So, time to index did increase, but performance also decreased. I suppose that should be expected - while that "long pole" effect of batching requests increases the total time to index, it also provides for some idle time to keep that CPU% down.

I'm liking 100/180 under this configuration, although the indexing time is still pretty high. Will profile again and see if there are some spots in the code where performance could be directly improved, and then revisit those numbers to try to get indexing time down.

**Comment by larkin** [comment]
Subjectively, what does an interval of 0 do to user interface responsiveness?  It should be possible to have high cpu usage and retain a responsive ui.

Pete

On Sep 29, 2015, at 6:35 PM, Victor Woeltjen <notifications@github.com<mailto:notifications@github.com>> wrote:


Issuing separate getObjects calls per-id, with a maximum current number of ids (size) and indicated interval between new requests gives:

Size    Interval (ms)   CPU%    Time (s)
1000    10      100-120 [:x:]   39 [:white_check_mark:]
300     200     45-55 [:x:]     63 [:ok:]
250     100     65-70 [:x:]     47 [:white_check_mark:]
100     200     33-40 [:ok:]    121 [:x:]
100     180     33-40 [:ok:]    108 [:ok:]
100     150     37-45 [:ok:]    101 [:ok:]
100     100     45-50 [:ok:]    73 [:ok:]
75      150     35-40 [:ok:]    125 [:x:]
50      70      45-50 [:ok:]    100 [:ok:]
40      75      43-47 [:ok:]    128 [:x:]
40      50      50-55 [:x:]     99 [:ok:]
20      100     30-35 [:white_check_mark:]      286 [:x:]
10      20      50-60 [:x:]     172 [:x:]

So, time to index did increase, but performance also decreased. I suppose that should be expected - while that "long pole" effect of batching requests increases the total time to index, it also provides for some idle time to keep that CPU% down.

I'm liking 100/180 under this configuration, although the indexing time is still pretty high. Will profile again and see if there are some spots in the code where performance could be directly improved, and then revisit those numbers to try to get indexing time down.

**Comment by VWoeltjen** [comment]
Responsiveness of the UI is fine; indexing takes a little over 30 seconds.

I'd be strongly resistant to saturating the CPU like that on page load, though, particularly for deployments where we know a lot of other applications will be running concurrently. With a shared worker this might be reasonable (so that you only take the hit on the first tab)

**Comment by larkin** [comment]
Selfish me would leave it to the operating system to properly allocate resources to various applications.

I do think we need to look at dependency loading with regards to angular and requirejs and code reuse and etc.  If we'd only had a single non-angular dependency loading system, it would be trivial to move the entire operation to a shared web worker.

**Comment by VWoeltjen** [comment]
In the absence of requirements around CPU utilization, I guess I can't say it's wrong to do this. (This could help us discover those requirements.)

Dependency loading with requirejs [is being considered](https://github.com/nasa/openmctweb/blob/api-redesign/docs/src/design/proposals/APIRedesign.md#requirejs-as-dependency-injector) :grinning: ; I'll add a note there about this additional benefit.

This also gets back to my original concern about engineering effort; if making in-browser indexing perform acceptably is contingent on fundamental changes to the way dependencies are loaded, then is in-browser indexing really a smart investment? Google.com doesn't make an XHR to every page on the internet to build up a search index when _it's_ first loaded.

**Comment by larkin** [comment]
Logical fallacies aside, the underlying issue is our code is not portable or reusable within the same project because of the current dependency loading system.

**Comment by VWoeltjen** [comment]
Don't disagree that there are portability issues ("not reusable" is an overstatement - you can elect to make something reusable by exposing it as a service), but if we choose to address those, it should be because they add value or satisfy a need elsewhere. 

Filed a pull request for these changes. Still not totally happy with memory utilization, but have run out of obvious candidates for reducing this, and again - want to bound development effort here. Think we are okay for our immediate goals.
