### ISSUE TITLE
New Edit Mode details

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#161]
UI discussion, 9/28/15 Victor, Jay and Charles:
- Add "Save" to Save button.
- Ability to optionally choose textual labels to appear with icon buttons.

Possible order of features:
1. New edit layout: tree on left, drag from tree to initiate edit.
2. Move fixed position out of Panels into layouts. Allow layouts in layouts.
3. Evaluate if sub-object editing is actually needed.

From discussion, 9/28/15 Victor, CH, Andrew.
- Tree should reflect object edit changes as they happen. So if user drags in several telem objects but doesn't click Save, the tree will still update to reflect the state in the edit area. Those new objects should be visually flagged as "not yet saved". This is related to #159. This applies to addition, removal, renaming.
- Navigation in tree without unsaved changes should display a "Warning: you'll lose unsaved changes" dialog with an action to cancel - same as trying to nav out of current edit mode without saving.

**Comment by VWoeltjen** [comment]
In addition, think that we should disable Context Menu actions in the tree while in Edit mode. (Esp. with linking, this could allow strange things where a user edits something in the tree that they are also modifying in Edit mode, which may result in strange behaviors.)

Also, would like to see some guidance in the UI about how to present a linked instance of a dirty object in the tree when that object has been edited in Edit mode but is not in the tree being Edited.

**Comment by charlesh88** [comment]
Design elements to add as well:
- Multiple select and manipulate in the canvas area
- Elements pool as component in Inspector pane

**Comment by charlesh88** [comment]
@VWoeltjen @akhenry @larkin Here's what I think is the base level of NEM for release: items 1, 2 and 3 above. 4 would be nice but isn't essential IMO. Can you guys please weigh in? What am I missing? I'll pester you tomorrow 11/10 about this, as it's going to drive some of Andrew's effort in this sprint.

**Comment by charlesh88** [comment]
Some questions: 
* User is editing a layout that contains the original of a panel. The panel has multiple links of itself elsewhere, in folders and other objects. The user deletes the original using the Elements pool of the layout. What happens in the tree?

**Comment by akhenry** [comment]
Some additions to the features list based on my work for this sprint:
* Create button does not show dialog, goes straight into edit mode
* Navigating away from object being edited results in prompt to save or discard.

**Comment by larkin** [comment]
@charlesh88 my weigh in: Anything that was in edit mode before, should be in new edit mode.  I agree with 1,2, and 3 being "must haves," but in their bare minimum fashion.  I don't think we need #4, and I see #7 as necessary-- it's in current edit mode, we shouldn't toss it.  If a view has an toolbar, display it.

Specific points:
1. Disallow all.  If we decide something is necessary, figure it out then.
2. As simple as a CSS class, styling could be updated and iterated on.  "dirty object" isn't a user concern, but "currently being edited" is; we shouldn't spend too much time on this for v1.
3. Necessary.
4. If a view currently has an edit toolbar, display it.  Shouldn't be hard to drop that code in.

Finally, for your questions:
* technically, we don't have delete yet, so I'd say we punt on this.  But, if we had delete and didn't consider this a edge case, deleting an original in a layout would break it.
* Agree.
* Yes; There are other bugs that will prevent this doing that (e.g. layout doesn't support multiple of one thing but fixed position does-- when merged, it will be true).

**Comment by akhenry** [comment]
Also, there was discussion at some point about repurposing panels as "groups". I like this idea, because I think it makes their role a little clearer.

**Comment by VWoeltjen** [comment]
Agree with starting off with 1,2,3. I'm hesitant to defer 7 because it makes Fixed Position unusable, and makes Timeline hard to use.

> 1. Disallow all (?) context menu actions on tree items during edit mode. Are there any context menu actions it would make sense to keep?

I'd say disallow all or disallow none at the start. We could try user-testing with these enabled; the problem here (observed in MCT on the desktop) is that there can be cases where it is not clear to the user that the stuff on the left is saved, and the stuff on the right is unsaved. The New Edit Mode border might disambiguate this sufficiently, or it might not.

> 2. While in edit mode, flag the currently selected item (as well as all linked instances of the object currently being edited) in the tree with a "pending update" visual status. Connected to Victor's comment above about presenting a linked instance of a dirty object. Needs UI

I'd broaden this to include any objects that have unsaved changes from Edit mode, including their links (not just the selected object.) This happens often in a timeline, but can happen in a Layout too (you can Edit Properties on a panel in a layout)

> 4. Create menu filtered to only allow creation of items that can be contained by the currently selected

I'd defer this, partly because I'm not sure it's the right thing to do. There are cases where we want to be able to create things while editing and place them more deeply in the hierarchy, particularly as we move toward a "edit panels inside of a layout" approach. I think the right thing to do in that case is filter down based on what's contained in the whole subgraph being edited (which may require loading a lot of objects just to figure out; we could end up with a wait spinner in the Create menu) which is different enough that I'm inclined to defer.


>    User is editing a layout that contains the original of a panel. The panel has multiple links of itself elsewhere, in folders and other objects. The user deletes the original using the Elements pool of the layout. What happens in the tree?

I think the Delete should not take effect until the user Saves. It would be really scary to me as a user if _some_ of my actions in Edit mode were immediate, and others could be cancelled.

If the user drags the object back in after a Delete, though, well, that's weird. Do we say "that thing doesn't exist in the little version of the world that you're editing"? Do we cancel the Delete?

After Save, I think all links in the tree should be replaced with Missing Objects.

>    Can the user drag an object's child into itself again? I think you should, the action would add another linked version of the object being dragged (once/if we allow multiple instances of the same object in a layout, for example).

Hm. Multiple linked instances of the same object seems weird to me, and we'd have to change the way we model location to accommodate this. I do think we should allow multiple occurrences of the same object in frames in a Display Layout, but I don't see the need to represent them multiple times in the Elements pool or the tree.

**Comment by charlesh88** [comment]
Thanks all. My comments:
* Agree on 7, that is needed, particularly for Timelines.
* Agree on disallowing all context actions in the tree during editing.
* Ok with Elements pool being needed for NEM v1.
* On 4 (filtered Create menu while editing an object): invoking Create while editing in NEM currently limits the user to saving in a hierarchy that starts with the outermost object being edited. If the user can create objects that can't actually be saved anywhere in the hierarchy where they are working, that sucks. All that said, I agree this could be deferred for NEM v1.
* Totally agree on deletion not taking effect until a Save event on the object being edited.
* On the question about what happens in the tree when an original is deleted from another object being edited, I'm fine with the approach that the tree doesn't update until a Save event occurs in the object being edited. 
 * That said, the scenario where a user drags a deleted original back in to an object being edited *is* weird. Not sure what to do here, and I think that we'll need to dig more into this when deletion is being implemented.
 * As for what happens to the links that point at a deleted original, when we begin to implement deletion, we should re-examine how we want to handle this: there are pros and cons to both approaches of replacing links with missing objects (lots of leftover cruft) or just deleting the links too (WTF happened to my links?).
* Multiple instances of a single object in a layout was the use case that was top of mind for me. I do think they would need to be represented multiple times in the Elements pool, but not in the tree. The rationale here is the role that an enhanced Inspector could play in edit mode: all objects (including boxes and lines) might manifest in the Elements pool. The notion is that the Elements pool is just an alternate representation of *everything* within an object.

**Comment by charlesh88** [comment]
@VWoeltjen @larkin @akhenry I have versioned the UI sketches for this in Google Docs: https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing
Notable changes:
- Pg 22: Editing overview, covers how to present items in the tree that are currently being edited.
- Pg 36: Elements pool added to the Inspector.

**Comment by charlesh88** [comment]
Checking in on the status of our identified NEM v1 features, numbers as above:
1. #277: Progress?
2. #278: Charles to stub in CSS today, hand over to Andrew for wiring.
3. #279: Charles made good progress on markup and CSS on this last week, hopes to finalize and deliver to Andrew today.
7. #284: Progress?
11. #287: Progress?

**Comment by akhenry** [comment]
#277 No progress to date
#284 No progress to date
#287 Good progress. Functionally complete, has introduced a bug with auto-created panels which I will fix today.

My priorities for Banks currently are #287, #277, #286. If #278 and #279 are ready soon, then it might make sense to prioritize them over #277 and #286

**Comment by charlesh88** [comment]
As of today, my deliverables on 1,2 and 3 (#277, #278 and #279 respectively) are complete. 7, 10 and 11 (#283, #286, #287) don't need any frontend or additional design.
@akhenry If I can help with any of this, please let me know.

**Comment by akhenry** [comment]
Thanks @charlesh88, will do!

**Comment by akhenry** [comment]
#283 Done
#286 Done
#287 Done
#278 In progress
