### ISSUE TITLE
Cannot scroll in layouts and fixed position view

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#232]
It seems that as of the lastest build, it is not possible to scroll in a layout view, even if content exists off screen.  The scroll bar is not visible, and the view does not response to the scroll wheel or other methods of scrolling.

scrolling views and item views still scroll properly.

**Comment by larkin** [comment]
Quick checking shows that this was working properly before the resolution for #195 was merged.  Sending to @VWoeltjen for investigation.

**Comment by VWoeltjen** [comment]
Looking into this - this occurs because the relevant styles reference `ng-include`, which is no longer used/useful after changes for #195.

Changing `.object-holder > ng-include` to `mct-representation.object-holder` in CSS files for themes appears to address the issue. Reassigning to Charles to complete the fix in the original SASS

**Comment by VWoeltjen** [comment]
@charlesh88  - a little bit more background on this. #195 was solved by:

* Swapping out `mct-representation` and `mct-include` elements with comments when there is nothing to show
* Instead of using `ng-include` to load the inner template, template contents are loaded directly into `mct-representation`. (This is the change which triggered this issue.) This allows for detecting cases where a template can not be loaded (which `ng-include` doesn't support)

**Comment by charlesh88** [comment]
Working on this now. Will be open232, branched from master.

**Comment by charlesh88** [comment]
Pull request filed as #236

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  Verified this is working now
