### ISSUE TITLE
[build] Upgrade PhantomJS to v2. 

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#258]
Our builds are currently based on PhantomJS v1.9. Pre 2.0 versions of PhantomJS are based on an outdated version of WebKit that is missing support for certain ES5 functionality, eg. function.prototype.bind().
see 
* Issue https://github.com/ariya/phantomjs/issues/10522 
* and discussion at https://groups.google.com/forum/#!msg/phantomjs/r0hPOmnCUpc/uxusqsl2LNoJ

**Comment by larkin** [comment]
I had looked into this before, requires rewriting the phantomjs test runner in javascript as 2.0 doesn't allow coffeescript.

the main blocker I found at that time was that there isn't a universal linux binary for phantomjs, so mvn couldn't install phantomjs in our continuous integration environments. this may have been resolved now; I can't remember where the specific ticket for that went.

**Comment by larkin** [comment]
Here's the old commit for it: https://github.com/nasa/openmctweb/commit/62f335573a0792cd7d82ddd8f61c73866f547cbf

**Comment by VWoeltjen** [comment]
This is trivial after #642, since the test runner is removed. May address this in the context of #649 (I'll want to use `Blob` there, which Phantom 1.x does not support.)

Regarding the lack of a universal linux binary, not sure why this would be a problem under Maven and not NPM, except that this is more commonly-used under NPM so Maven plugins may be less up-to-date. But tests in #642 are running/passing on CircleCI, so it's getting a Linux PhantomJS somehow

**Comment by larkin** [comment]
@VWoeltjen linux binary for phantomjs 2.0 didn't exist; this would break our continuous integration machines-- they were unable to install the dependency which means tests would fail.

As of 2.1 the issues with the binary for phantonmjs are resolved, so if we go straight to 2.1 we will be fine. https://github.com/ariya/phantomjs/issues/12948

**Comment by VWoeltjen** [comment]
@larkin Thanks for explaining/clarifying, have bumped to 2.1 on topic branch for #649

**Comment by VWoeltjen** [comment]
Addressed by https://github.com/nasa/openmctweb/commit/54c67b891c21cff84d7eb5e5af168d0eae0460e3
