### ISSUE TITLE
[Layout] Layout rebuilds after resize/reposition

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#32]
In Edit mode of a Display Layout containing multiple panel, drag one panel. Observe: Contents of other panels are reloaded (can be seen to repopulate)

Desired behavior is that the position of the dragged panel updates, but that it contents remain as they were.

**Comment by akhenry** [comment]
Have done some initial investigation. Notes below.

1. The refresh is happening because the drag gesture updates the _configuration_ of the layout object being edited.
1. This change is then persisted (via the EditablePersistenceCapability - which just marks the editable object cache dirty).
1. This has the effect of updating the 'modified' value on the domain object model
1. This triggers a watch in MCTRepresentation which updates the objects capabilities
1. One of those capabilities is the view capability, so $scope['view'] gets set to a list of the views for this object. __it seems to be this step that triggers the redraw of all children__ Don't know enough about what the implication of setting that property of scope is to speculate about why that is yet.

**Comment by akhenry** [comment]
Fixed in PR #345

**Comment by RCarvalhoNASA** [comment]
Testathon 20151207 This behaves much better now, really nice!

**Comment by charlesh88** [comment]
Testathon 20151207: Same experience as Robert.
