### ISSUE TITLE
Duplicate of layout containing images didn't maintain the position and size of the images

### ISSUE THREAD

**Issue by Costigan** [nasa/openmctweb#332]
During test-a-thon, I duplicated My Issues >> mshirley >> Mastcam Images.  The second one has possibly default positions and sizes for the images.

**Comment by VWoeltjen** [comment]
Believe this is a bad interaction between the way duplication is performed, and the way positions/sizes are stored for layouts:

1. When duplication occurs, the new objects get new identifiers. Existing `composition` properties get rewritten with the new identifiers.
2. Positions/sizes for objects in a layout are specified per-identifier. (Believe that currently this is in an object where IDs are keys and position/size objects are values; this would be better as an array of id/position/size objects to allow the same object multiple times in a layout, but we'd still see this problem)

Some options to solve this:

* Rewrite the identifiers in the Layout configuration on duplicate.
  * This is a bit of a challenge, because Duplicate shouldn't have any specific information about Layout view, but it also can't just presume to find-replace identifiers throughout the whole model. (Well, it could, and I'd expect it to work 99.9% of the time, but eventually we'd have a collision between an identifier and some unrelated string property/value in the model, and strange behavior would ensue.) Could introduce a new extension category (or extend the `views` extension category) to include some information (or just methods to call) to inform this rewrite process.
* Don't store identifiers in view configurations. Instead, use index in composition or similar.
  * This could make it challenging to keep views in sync with composition. The Layout view isn't necessarily even active while changing a Display Layout's composition. 

This may or may not be a problem for the `relationship` capability as well (this is only used for Activities and Activity Modes currently). Since this is a core property it would be reasonable to rewrite this explicitly during Duplicate.

**Comment by VWoeltjen** [comment]
Assigning to @akhenry for now (since he's worked on both Duplicate and on Layouts). Should reconsider assignments during sprint planning.

**Comment by larkin** [comment]
I believe the find/replace strategy will work in 100% of cases right now-- all objects that can be duplicated will have a GUID, and the likelyhood of a GUID matching some unrelated property/value is absurd.  It's also very cheap to implement: `JSON.stringify` the new object's model, call `modelString.replace(oldIdentifier, newIdentifier)` for each new composed object, and then call `JSON.parse` on the string to get the model with all identifiers migrated.

**Comment by VWoeltjen** [comment]
Good point - agree that find-replace on a GUID is safe. Not confident that this will only occur for objects with generated IDs currently; think this would be the case if we had better policy controls on duplication (as noted in #338.) If these changes are made in concert (within the same sprint, for instance), then I think that find-replace approach is quite reasonable. (It does seem a little brittle - change the way IDs get generated and Duplicate may break in subtle ways - but don't think that risk is great enough to warrant the level of effort needed for a more robust solution.)

**Comment by akhenry** [comment]
Wouldn't be difficult to write a regex to make it a little more targeted in order to reduce the risk of unwanted side effects.

**Comment by larkin** [comment]
Aside from wrapping the identifiers with quotes to prevent substring matches (e.g. if id is `abc` then `"abc"` would match `{"abc": "def"}` but not `{"abcd": "def"}`), it's hard to know when replacing any exact string match would be incorrect without more knowledge of the underlying structure.

And considering that policy controls on duplication will generally prevent duplicating non-uuid identifiers, seems unnecessary to go much further at this time.

**Comment by VWoeltjen** [comment]
@akhenry may have limited time to work on this - if so, reassign to @VWoeltjen

**Comment by VWoeltjen** [comment]
Resolved by #394
