### ISSUE TITLE
Plot datetimes focus on the wrong end

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmctweb#337]
If a plot/panel is relatively small on the display (within a layout, e.g.), the datetime indicators on the vertical lines are compressed, but they try displaying the datetime from the left rather than the right.  So moderately small plots will show the date but not the times, and very small plots will only show the year (or even part of the year).  Would seem this should be better scaled and managed so that the information about each line which is different would be favored over that which is identical.

**Comment by charlesh88** [comment]
@RCarvalhoNASA You mean the X axis time labels in a plot view, yes?

**Comment by RCarvalhoNASA** [comment]
Yes

**Comment by charlesh88** [comment]
Tick label strings are now reversed in their char order in PlotTickGenerator.js, then reversed again via CSS in _plots-main.scss. This forces the browser to clip the label at the left 'start' side, rather than the end, resulting in the least significant portion of the label getting clipped.

Work pushed to open337 and pull request #477 created, but code isn't passing CircleCi - get some help on this.

**Comment by RCarvalhoNASA** [comment]
Verified as fixed 20160209 Testathon
