### ISSUE TITLE
[Copy] Copying an object with telemetry from the data dictionary results in a number of unknown objects in copied tree

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#338]
Duplicate an object with children based on data dictionary points. A good example of this is My Items > RP15 Layouts > Battery Layout.

Object is duplicated ok, but the duplicated object contains unknown objects as children. The javascript console shows a large number of 404 errors during the copy process.

Suspect this is the same issue as #329 . It is probably caused by the fact that duplication is attempting to use the persistence space of the parent of the object being duplicated. Instead it should use the persistence space of the copy destination.

**Comment by larkin** [comment]
It may also be interpreting the data dictionary points as having a persistence identifier already (data dictionary points follow a very similar format for storing data), which may have weird behavior.

The underlying issue here is that data dictionary points should not be duplicated-- they should be linked to instead.  Need some logic that prevents duplicating objects which cannot be created (and instead creates links to those objects).

**Comment by akhenry** [comment]
Looking to implement this week. @VWoeltjen @larkin, what is the logic to be applied here? Is there an applicable capability I should check? (eg. do data dictionary entries have a persistence capability?). Also, what's the correct action here, i assume it's to create links for the objects that should not be directly copied?

**Comment by VWoeltjen** [comment]
Platform support for this is currently pretty poor. The best approximation we have is `domainObject.getCapability('type').hasFeature('creation')`.

Think we should add a `mutation` policy category in this issue and start using that instead (perhaps implementing  a policy instance that calls the above to ensure compatibility). A number of actions will need to check this, I think; the `composition` policy is currently pretty well-checked by actions so we'd get a long way there if we had a `composition` policy instance that delegated to `mutation` ("only allow composition in things that can be mutated.") 

Alternately, we could restrict the presence of the `mutation` _capability_ to things which can actually be mutated (and add a `capability` policy to restrict its presence, if we don't have one.) Thinking a `mutation` policy category is more likely to survive an API Redesign at this point (and also allows us to continue using `mutation` as a capability for things the user can't change.)

**Comment by larkin** [comment]
Note that an object that does not have a mutation capability could still trigger mutate events (I.e. Changing a dataset dictionary should trigger mutate on all children). 

Seems like it is safe to detect edit ability from mutation though.

**Comment by akhenry** [comment]
Ok, so for clarification, the changes I am going to make for this issue are:

1. Create a new mutation policy category and instance. For now the MutationPolicy (or TypeCreatabilityPolicy ?) instance will check that
`domainObject.getCapability('type').hasFeature('creation'`
2. Modify the duplication service to use the persistence space of the copy target, not the object being copied

**Comment by VWoeltjen** [comment]
Backtracking to the original issue, I'm thinking this should be a "creation" policy and not a "mutation" policy. The two are effectively synonymous now, but we shouldn't be encoding that everywhere - most sensible thing for copy to ask is "can I create an object of this type?" (`policyService.allow('creation', domainObject.getCapability('type')`)

> 1. Create a new mutation policy category and instance. For now the MutationPolicy (or TypeCreatabilityPolicy ?) instance will check that domainObject.getCapability('type').hasFeature('creation'

Yep - with the caveat that based on the above I'd name it CreationPolicy. (I think we should have a mutation policy category too, but that's out of scope for this issue)

> 2.  Modify the duplication service to use the persistence space of the copy target, not the object being copied

Yep. I would do this by using the `instantiate` capability of the copy target to minimize the amount of knowledge that Copy needs.

I'd add a 3 to say that CreateActionProvider should be using this policy (instead of `hasFeature('creation')` directly.) 

There are other places in the code where we ask `domainObject.getCapability('type').hasFeature('creation')` when we really mean `policyService.allow('mutation', domainObject)` but again, I'd consider that out of scope for this issue.

**Comment by akhenry** [comment]
@VWoeltjen Sounds good. On it.

**Comment by charlesh88** [comment]
Testathon 20151207: verified
