### ISSUE TITLE
Issue at deploying my webapp in Azure

### ISSUE THREAD

**Issue by fillocj** [nasa/openmctweb#489]
The app runs fine in localhost, but  when I deployed in azure the link seems to be in blank. This is the link: http://mctweb.azurewebsites.net does anyone know why this happens? I deployed it through github

Thanks a lot.

**Comment by akhenry** [comment]
Great to hear you're trying out Open MCT Web.

When I visit http://mctweb.azurewebsites.net I get an internal server error -
```
http://mctweb.azurewebsites.net/index.html Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

This means that the error is occurring within your web application. What kind of server side infrastructure have you deployed it on? Are you running app.js as a node.js application, or are you simply hosting Open MCT Web from an http server? I would recommend the second.

**Comment by fillocj** [comment]
I deployed it with github repository. Could you please tell me what to do to deployed well?

**Comment by akhenry** [comment]
Apologies, my question wasn't clear. What are you running on your Azure server? Is it a simple http server, or a node.js server, or a .NET web container? Open MCT Web is a client application, and from the error message I am seeing there is something wrong on the server hosting it.

**Comment by fillocj** [comment]
So there is no way to deploy it in a server? As an app for everyone is my question?. I ran it as node.js server, maybe in Heroku could work?

**Comment by akhenry** [comment]
Absolutely you can deploy it to a web server. Open MCT Web is a single page javascript application, it's just HTML + javascript. So while it runs in the browser, it needs a web server to host it. You can use any web server you like, eg. apache, nginx, etc. 

The repository includes a basic node.js http server implementation - app.js, but this is just provided for convenience, so that you can run it on your local machine. I would not recommend using app.js for hosting Open MCT Web other than locally. Having said that, I can't think of a reason why the provided node.js application would not work on Azure, but it might be a problem with permissions and/or dependencies. Are you able to check the server logs?

We have had success hosting Open MCT Web on Heroku, so that might be an avenue to explore. It doesn't even need a PaaS solution though, you could host it in an Amazon S3 bucket. Basically anything that can host HTML.

**Comment by fillocj** [comment]
Excellent, I will try it a little later. Thanks a lot Henry! :D

**Comment by akhenry** [comment]
Happy to help!

**Comment by akhenry** [comment]
@fillocj Did you have any luck?

**Comment by fillocj** [comment]
Unfortunately I have not had enough time to make it possible so far. I will let you know if I have success with the deployment on azure.

**Comment by fillocj** [comment]
https://nasactm.herokuapp.com here's the web! This is what I wanted to do.

**Comment by akhenry** [comment]
Great! Glad you managed to get it working. I'd love to hear about what you do with it!

If you'd like to contribute to our code, please let me know and I can send you some documentation to enable this to happen.

**Comment by fillocj** [comment]
Sure I'd love to contribute. My email is rcalvosas@gmail.com I'll make a little tutorial how I deployed it. Regards and thanks in advance @akhenry

**Comment by akhenry** [comment]
Since this issue has been resolved I am closing this ticket.
