### ISSUE TITLE
Can't dismiss errors as a result of notification

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#499]
@charlesh88 is reporting that error notifications can't be dismissed in the notifications window.  This has been seen with errors from duplication and persistence.

Reproduction:

1. Include `'./example/notifications/bundle'` in main.js
2. launch application
3. in the status bar, trigger an error notification.
4. click the "notification" alert menu
5. try to dismiss the error by clicking any buttons.  note that the error will not be dismissed.

**Comment by larkin** [comment]
I want to highlight here the importance of blocking dialogs and notifications being two separate apis that should have separate usage.  It's not telling the user the same thing twice.  It's telling them two separate things.  The actions available in a blocking dialog could be significantly different than those in a notification.  

Duplicate failures are quite interesting:
* duplicate failures have a blocking dialog with "ok" button.
* duplicate failures may also have a notification, but it should auto-dismiss and/or be dismissable: the user will have seen the blocking dialog already.  The language should be different in each case.

**Comment by akhenry** [comment]
Blocking dialogs and non-blocking notifications are entirely separate APIs with similar, but slightly different usage. They are designed to be somewhat interoperable so that a notification options object can also be passed to the dialogService and vice-versa, largely as a consequence of sharing a substantial number of attributes. But they are separate entities, with no interdependence.

The issue here I think is in use of the API, rather than the API itself. I have an idea of what the issue is, and it should be relatively trivial to fix.

Error messages do auto-dismiss if another error messages comes along, and can be manually 'minimized' out of the notification bar. They cannot currently be dismissed entirely though. This was by design, I guess so that users could always refer back to it if they needed to? Perhaps we should reconsider this and allow users to dismiss notifications completely once they're in the notifications list. Or just allow them to dismiss them directly from the notification bar.
