### ISSUE TITLE
[CSV Export] Allow CSV export of telemetry

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#654]
Add an action to allow CSV export of telemetry for:

* Individual telemetry points.
* Groups of telemetry points (e.g. telemetry panels)

This should utilize query bounds from the time conductor (if the time conductor is available)

**Comment by larkin** [comment]
I would prefer not to implement this as a generic as it has limited value at this time[1].  Right now every historical telemetry store is paginated (and sometimes with horrible/nearly nonexistent pagination support), and thus it's going to require some very specialized logic to get it working in the short term, and will probably require writing some code that has questionable value to the open platform.  

[1] it could potentially bring us value for the progress dialog but I think we are liable to overthink that dialog in the time frame we have.

**Comment by VWoeltjen** [comment]
I think I understand your point, but I'm wondering why the pagination issue is specific to CSV export. Wouldn't we run into the same problem when viewing historical telemetry? I would expect to solve this in the TelemetryProvider for those sources

**Comment by larkin** [comment]
A days worth of telemetry for a single channel is easily 5-10 mb.  Add a few channels and you have a large file.  The client shouldn't request it all unless it knows it will display it all, and with time conductor it's easy to accidentally request huge time ranges that you really didn't need.  But because there is no request cancellation in the telemetry api, there's no way to stop an accidental request after it was sent.  Currently, we can't make auto-pagination the default, but we can't ignore it completely.  

As far as viewing historical telemetry, as the server doesn't support pagination and we've been able to say "if you request more data than the server can return in a single request, your results may be truncated".  Since the server does not tell us when this occurs, we don't have to communicate it to the user in a view.

Now, I do feel there are expectations that csv export will export all the data, and that is where we can implement alternative code to handle pagination in the short term, without committing to it as an API level change. I'd like to focus on figuring out what it takes to implement this in the scope of a specific requirement without implementing the full-stack solution.

I do suppose, that we could ignore all this and ignore pagination completely and go for the generic solution.  That would probably meet the requirement but we'd need to list the known issues still.

**Comment by VWoeltjen** [comment]
Thanks for clarifying, I have a better understanding of the problem now. 

> As far as viewing historical telemetry, as the server doesn't support pagination and we've been able to say "if you request more data than the server can return in a single request, your results may be truncated". Since the server does not tell us when this occurs, we don't have to communicate it to the user in a view.

If the server does not tell us when this occurs, how does a non-generic CSV export detect and handle this? Just request at "known safe" chunk sizes? Something else?

**Comment by VWoeltjen** [comment]
Having looked at the specific use case for this more closely, agree that generic solution is a misfit. (There are issues beyond the paging that would complicate a generic solution; there are columns which we want in CSV output which we may not want to express as domains/ranges, for instance.) Closing as wontfix, handling in a separate issue tracker.
