### ISSUE TITLE
[Create] Attempting to create a new object while a telemetry packet is selected fails

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#656]
To reproduce
1. Select a telemetry point under "Packets" (eg. Packets > ANTIO_DAT > TILT_VEL)
2. Click on the create button to create a new type, choose a Clock as an example
3. In the dialog, select a location that should allow creation of new user objects (such as My Items)
4. Attempt to save the new object. The persistence step will fail.

The mode of failure suggests that it is attempting to use the persistence store of the parent originally selected (ie. the telemetry point), rather than the location selected from the create dialog.

**Comment by VWoeltjen** [comment]
Basic issue here is that packets have a prefixed identifier, which makes them appear to belong to another persistence space. That part is reasonable - they come from a dictionary which is reasonable to treat as a persistence space, excepting that it is read-only.

When the `instantiation` capability is used on such an object, however, the newly-created object inherits the persistence space of the object that was selected. Think this makes sense in general, but in cases where that space is non-writable, think it should fall back to using the default space.

The trick is to actually recognize that a space is or is not writable. The practical way to do this is to use `persistenceService.listSpaces()`, but that returns a Promise, whereas the `instantiation` capability is synchronous. Closest relevant place in the system where behavior is asynchronous is in the `objectService`; will consider fixing this there.

**Comment by larkin** [comment]
Because we don't actually persist the object until later in the process, shouldn't we choose the persistence space based on the location chosen in the save dialog?

**Comment by VWoeltjen** [comment]
Yes; or, I think so. The difficulty comes from three rules:

1. All domain objects have identifiers.
2. Persistence space is encoded in identifiers.
3. Identifiers are immutable.

Taken on their own, these are all reasonable, but these create challenges in NEM, where workflow is to edit the object _before_ choosing where to persist it. We need a domain object to begin editing, which per Rule 1 means we need an identifier, which per Rule 2 implies choosing a persistence space. We can't change our mind about this when a location is chosen without violating Rule 3. (Technically, we _could_ change our mind by effectively doing a duplicate with the appropriate identifiers chosen before saving, but that seems like a rather weird workaround to rules that don't fit the system well.)

Something's gotta give here, and I think it's Rule 2. Rules 1 and 3 are rather fundamental (and fairly sensible IMO) so it seems like the only option. If we move persistence space selection out of the identifier and into a service, then we could change our space selection without needing to rewrite compositions, et cetera. (It does pose a bit of an indexing problem, however, insofar as we need to know the persistence spaces for all identifiers at start up.)

Another "stressing case" for space selection is Duplicate. Here, we explicitly want to choose persistence spaces before adding objects to their destination, so that we end up in a reasonable state (if the computer gets unplugged, for instance.) So selection of persistence space needs to be independent of addition to composition.

In any event, have a [pull request](https://developer.nasa.gov/mct/warp/pull/137) for a quick-fix for this up. It's a band-aid but should get us unblocked.

**Comment by larkin** [comment]
Ultimately the problem we see is the instantiate service was written to assist in the duplicate process (in which we know the persistence space before the operation starts), and that doesn't map to how the new edit mode logic works.  We don't know the persistence space ahead of time, and that's okay-- we should just fix that, instead of rewriting our solution to a different problem.

So, on my side, I would rather treat this as an exception to the rule; and not rewrite the rules to satisfy this one case.  We can violate rule 3 and rewrite identifiers prior to persisting the objects.

**Comment by RCarvalhoNASA** [comment]
Testathon 20160211 this appears to work correctly now

**Comment by akhenry** [comment]
Testathon 20160211

Verification tries:

1. Select EPSIO_BIT, Create Folder
 * Got dialog, Save In "My Items" - got overwrite warning dialog, but think that could have been me and Andrew simultaneously modding My Items.
1. Tried 1 again, no problem.
1. Tried 1 again, Save In nested folder. No problem.
1. Select EPSIO_BIT, Create Layout. Added a telem elem, Save in My Items > CHacskaylo folder. No problem.

This appears to be fixed.
